import type { Metadata } from "next";
import "./globals.css";
import { TrpcWrapper } from "@/provider/trpc-wrapper";
import { ChakraWrapper } from "@/provider/chakra-wrapper";
// import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Script
          src="/static/datafeeds/udf/dist/bundle.js"
          strategy="lazyOnload"
        /> */}
        <TrpcWrapper>
          <ChakraWrapper>{children}</ChakraWrapper>
        </TrpcWrapper>
      </body>
    </html>
  );
}
